[build]
  command = """
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.0.35/quarto-1.0.35-linux-amd64.deb -O quarto.deb && 
    dpkg -x quarto.deb . &&
    ./usr/local/bin/quarto render
  """
  publish = "_site"
